### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AayanAsim746** [GuyPerson7018/dank-memer-miner#1]
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    hold.before_loop(bot.wait_until_ready())    
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 371, in before_loop
    raise TypeError('Expected coroutine function, received {0.__name__!r}.'.format(type(coro)))
TypeError: Expected coroutine function, received 'coroutine'.


**Comment by GuyPerson7018** [comment]
Fixed. Thanks for reporting this bug!
